<?php
/**
 * @package     Joomla.Site
 * @subpackage  com_content
 *
 * @copyright   Copyright (C) 2005 - 2019 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;
JHtml::addIncludePath(JPATH_COMPONENT . '/helpers');
$modules = JModuleHelper::getModules('dialog');
// Create shortcuts to some parameters.
$params  = $this->item->params;
$images  = json_decode($this->item->images);
$urls    = json_decode($this->item->urls);
$canEdit = $params->get('access-edit');
$user    = JFactory::getUser();
$info    = $params->get('info_block_position', 0);
// $itemRawValue = array();
foreach($this->item->jcfields as $field) :
	// данные
	$itemRawValue[$field->name] = $field->rawvalue;
	// значеине
	$itemFieldVal[$field->name] = $field->value;
	// class
	$itemFieldClass[$field->name] = $field->params->get('render_class');
	// заголовок поля
	$itemFieldTitle[$field->name] = $field->title;
	// группаID таблица
	$itemFieldGroup[$field->group_id] = $field->group_id;
	// параметры
	$itemFieldPar[$field->name] = $field->fieldparams;
endforeach;

// Check if associations are implemented. If they are, define the parameter.
$assocParam = (JLanguageAssociations::isEnabled() && $params->get('show_associations'));
JHtml::_('behavior.caption');
?>
<div class="container item-page<?php echo $this->pageclass_sfx; ?> accessory" itemscope itemtype="https://schema.org/Article">
	<meta itemprop="inLanguage" content="<?php echo ($this->item->language === '*') ? JFactory::getConfig()->get('language') : $this->item->language; ?>" />
	<?php if ($this->params->get('show_page_heading')) : ?>
		<h1 class="page-header page-header-menu"><?php echo $this->escape($this->params->get('page_heading')); ?></h1>
	<?php endif;
	if (!empty($this->item->pagination) && $this->item->pagination && !$this->item->paginationposition && $this->item->paginationrelative)
	{
		echo $this->item->pagination;
	}
	?>

	<?php // Todo Not that elegant would be nice to group the params ?>
	<?php $useDefList = ($params->get('show_modify_date') || $params->get('show_publish_date') || $params->get('show_create_date')
	|| $params->get('show_hits') || $params->get('show_category') || $params->get('show_parent_category') || $params->get('show_author') || $assocParam); ?>

	<?php if (!$useDefList && $this->print) : ?>
		<div id="pop-print" class="btn hidden-print">
			<?php echo JHtml::_('icon.print_screen', $this->item, $params); ?>
		</div>
		<div class="clearfix"> </div>
	<?php endif; ?>
	<?php if ($params->get('show_title') || $params->get('show_author') || !empty($itemFieldVal['headerh2'])) : ?>
	<div class="page-header">
		<?php if ($params->get('show_title')) : ?>
			<h1 class="page-header-article" itemprop="name"><?php echo $this->escape($this->item->title); ?></h1>
		<?php endif; ?>
		<?php if ($this->item->state == 0) : ?>
			<span class="alert alert-warning"><?php echo JText::_('JUNPUBLISHED'); ?></span>
		<?php endif; ?>
		<?php if (strtotime($this->item->publish_up) > strtotime(JFactory::getDate())) : ?>
			<span class="alert alert-warning"><?php echo JText::_('JNOTPUBLISHEDYET'); ?></span>
		<?php endif; ?>
		<?php if ((strtotime($this->item->publish_down) < strtotime(JFactory::getDate())) && $this->item->publish_down != JFactory::getDbo()->getNullDate()) : ?>
			<span class="alert alert-warning"><?php echo JText::_('JEXPIRED'); ?></span>
		<?php endif; ?>
		<?php // Content is generated by content plugin event "onContentAfterTitle" ?>
			<?php echo $this->item->event->afterDisplayTitle; ?>
	<?php // headerh2 ?>
	<?php if(isset($itemFieldVal['headerh2']) && !empty($itemFieldVal['headerh2'])) : ?>
		<h2 class="page-header-subarticle" itemprop="headline"><?=$itemFieldVal['headerh2']; ?></h2>
	<?php endif; ?>
	</div>
	<?php endif; ?>

		<?php // Content is generated by content plugin event "onContentBeforeDisplay" ?>
		<?php echo $this->item->event->beforeDisplayContent; ?>
	<div class="item-body">
	
	<?php $itemRawAccessory = json_decode($itemRawValue['accessory'], true); ?>
	<?php  if (isset($itemRawAccessory) && !empty($itemRawAccessory)) : ?>
		<div class="item-body-section">
			<?php foreach ($itemRawAccessory as $itemAccessory) : ?>
			<div class="accessory-card <?=$itemFieldClass['accessory']; ?>">
				<div class="accessory-row">
				<?php if (!empty($itemAccessory['img']) && !empty($itemAccessory['img']) ): ?>
					<div class="col-img miup">

				<?php // из ссылки вырезаем каталог
					$path_dirname = pathinfo($itemAccessory['img'])['dirname'];
					$path_basename = pathinfo($itemAccessory['img'])['basename'];
					$srcset = $path_dirname.'/big/'.$path_basename;
					if(file_exists($srcset)): ?>
						<a href="<?=$srcset?>" class="link card-link"><img srcset="<?=$itemAccessory['img']; ?>" alt="<?=$itemAccessory['name']; ?>" class="image accessory-img" /></a>
						<?php else : ?>
						<a href="<?=$itemAccessory['img']; ?>" class="link card-link"><img srcset="<?=$itemAccessory['img']; ?>" alt="<?=$itemAccessory['name']; ?>" class="image accessory-img" /></a>
					<?php endif; ?>
					</div>
				<?php endif; ?>
					<div class="col-table">
						<table class="table accessory-table">
						<?php if (!empty($itemAccessory['name']) && !empty($itemAccessory['name']) ): ?>
							<tr>
								<td colspan="2"><?=$itemAccessory['name']; ?></td>
							</tr>
							<?php endif; ?>
							<?php if (!empty($itemAccessory['diameter']) && !empty($itemAccessory['diameter']) ): ?>
							<tr>
								<td>Диаметр</td>
								<td><?=$itemAccessory['diameter']; ?> мм</td>
							</tr>
							<?php endif; ?>
							<?php if (!empty($itemAccessory['angle']) && !empty($itemAccessory['angle']) ): ?>
							<tr>
								<td>Угол</td>
								<td><?=$itemAccessory['angle']; ?>º</td>
							</tr>
							<?php endif; ?>
							<?php if (!empty($itemAccessory['size']) && !empty($itemAccessory['size']) ): ?>
							<tr>
								<td>Размер</td>
								<td><?=$itemAccessory['size']; ?></td>
							</tr>
							<?php endif; ?>
							<?php if (!empty($itemAccessory['width']) && !empty($itemAccessory['width']) ): ?>
							<tr>
								<td>Длина</td>
								<td><?=$itemAccessory['width']; ?></td>
							</tr>
							<?php endif; ?>
							<?php if (!empty($itemAccessory['weight']) && !empty($itemAccessory['weight']) ): ?>
							<tr>
								<td>Вес</td>
								<td><?=$itemAccessory['weight']; ?> мм</td>
							</tr>
							<?php endif; ?>
							<?php if (!empty($itemAccessory['amount']) && !empty($itemAccessory['amount']) ): ?>
							<tr>
								<td>Количество</td>
								<td><?=$itemAccessory['amount']; ?>  шт.</td>
							</tr>
							<?php endif; ?>
							
							<?php if (!empty($itemAccessory['text']) && !empty($itemAccessory['text']) ): ?>
							<tr>
								<td colspan="2"><?=$itemAccessory['text']; ?></td>
							</tr>
							<?php endif; ?>
						</table>
					</div>
				</div>
			</div>
			<?php endforeach; ?>
		</div>
	<?php endif; ?>
	
		<?php if (!empty($this->item->text) && isset($this->item->text)) : ?>
		<div class="item-section-fulltext fulltext" itemprop="articleBody">
			<?php echo $this->item->text; ?>
			
			<?php if (isset($urls) && ((!empty($urls->urls_position) && ($urls->urls_position == '0')) || ($params->get('urls_position') == '0' && empty($urls->urls_position)))
			|| (empty($urls->urls_position) && (!$params->get('urls_position')))) : ?>
			<?php echo $this->loadTemplate('links'); ?>
			<?php endif; ?>
			<?php if ($params->get('access-view')) : ?>
			<?php echo JLayoutHelper::render('joomla.content.full_image', $this->item); ?>
			<?php
			if (!empty($this->item->pagination) && $this->item->pagination && !$this->item->paginationposition && !$this->item->paginationrelative) :
				echo $this->item->pagination;
			endif;
			?>
			<?php if (isset ($this->item->toc)) :
				echo $this->item->toc;
			endif; ?>
		</div>
		<?php endif; ?>
		
		<div class="item-body-section">
			<div class="item-section-buy buy"><a class="btn" href="index.php?option=com_content&view=article&id=35"><?=JText::_('FIND_DEALER').'<strong> '. $this->item->title .'</strong> '. JText::_('FIND_MAP'); ?></a></div>
			<?php if (isset($itemFieldVal['brand']) and !empty($itemFieldVal['brand'])) : ?>
			<div class="item-section-brand brand<?=$itemFieldClass['brand']; ?>">
				<img src="<?=$itemRawValue['brand']; ?>" alt="brand-<?=$this->item->category_title?>" class="image item-section-brand_image">
			</div>
			<?php endif; ?>
		</div>
	</div>

	<?php if ($info == 1 || $info == 2) : ?>
		<?php if ($useDefList) : ?>
				<?php // Todo: for Joomla4 joomla.content.info_block.block can be changed to joomla.content.info_block ?>
			<?php echo JLayoutHelper::render('joomla.content.info_block.block', array('item' => $this->item, 'params' => $params, 'position' => 'below')); ?>
		<?php endif; ?>
		<?php if ($params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) : ?>
			<?php $this->item->tagLayout = new JLayoutFile('joomla.content.tags'); ?>
			<?php echo $this->item->tagLayout->render($this->item->tags->itemTags); ?>
		<?php endif; ?>
	<?php endif; ?>

	<?php
	if (!empty($this->item->pagination) && $this->item->pagination && $this->item->paginationposition && !$this->item->paginationrelative) :
		echo $this->item->pagination;
	?>
	<?php endif; ?>
	<?php if (isset($urls) && ((!empty($urls->urls_position) && ($urls->urls_position == '1')) || ($params->get('urls_position') == '1'))) : ?>
	<?php echo $this->loadTemplate('links'); ?>
	<?php endif; ?>
	<?php // Optional teaser intro text for guests ?>
	<?php elseif ($params->get('show_noauth') == true && $user->get('guest')) : ?>
	<?php echo JLayoutHelper::render('joomla.content.intro_image', $this->item); ?>
	<?php echo JHtml::_('content.prepare', $this->item->introtext); ?>
	<?php // Optional link to let them register to see the whole article. ?>
	<?php if ($params->get('show_readmore') && $this->item->fulltext != null) : ?>
	<?php $menu = JFactory::getApplication()->getMenu(); ?>
	<?php $active = $menu->getActive(); ?>
	<?php $itemId = $active->id; ?>
	<?php $link = new JUri(JRoute::_('index.php?option=com_users&view=login&Itemid=' . $itemId, false)); ?>
	<?php $link->setVar('return', base64_encode(ContentHelperRoute::getArticleRoute($this->item->slug, $this->item->catid, $this->item->language))); ?>
	<p class="readmore">
		<a href="<?php echo $link; ?>" class="register">
		<?php $attribs = json_decode($this->item->attribs); ?>
		<?php
		if ($attribs->alternative_readmore == null) :
			echo JText::_('COM_CONTENT_REGISTER_TO_READ_MORE');
		elseif ($readmore = $attribs->alternative_readmore) :
			echo $readmore;
			if ($params->get('show_readmore_title', 0) != 0) :
				echo JHtml::_('string.truncate', $this->item->title, $params->get('readmore_limit'));
			endif;
		elseif ($params->get('show_readmore_title', 0) == 0) :
			echo JText::sprintf('COM_CONTENT_READ_MORE_TITLE');
		else :
			echo JText::_('COM_CONTENT_READ_MORE');
			echo JHtml::_('string.truncate', $this->item->title, $params->get('readmore_limit'));
		endif; ?>
		</a>
	</p>
	<?php endif; ?>
	<?php endif; ?>
	<?php
	if (!empty($this->item->pagination) && $this->item->pagination && $this->item->paginationposition && $this->item->paginationrelative) :
		echo $this->item->pagination;
	?>
	<?php endif; ?>

	<?php if (!$this->print) : ?>
		<?php if ($canEdit || $params->get('show_print_icon') || $params->get('show_email_icon')) : ?>
			<?php echo JLayoutHelper::render('joomla.content.icons', array('params' => $params, 'item' => $this->item, 'print' => false)); ?>
		<?php endif; ?>
	<?php else : ?>
		<?php if ($useDefList) : ?>
			<div id="pop-print" class="btn hidden-print">
				<?php echo JHtml::_('icon.print_screen', $this->item, $params); ?>
			</div>
		<?php endif; ?>
	<?php endif; ?>

	<?php if ($useDefList && ($info == 0 || $info == 2)) : ?>
		<?php // Todo: for Joomla4 joomla.content.info_block.block can be changed to joomla.content.info_block ?>
		<?php echo JLayoutHelper::render('joomla.content.info_block.block', array('item' => $this->item, 'params' => $params, 'position' => 'above')); ?>
	<?php endif; ?>

	<?php if ($info == 0 && $params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) : ?>
		<?php $this->item->tagLayout = new JLayoutFile('joomla.content.tags'); ?>

		<?php echo $this->item->tagLayout->render($this->item->tags->itemTags); ?>
	<?php endif; ?>

	<?php if ($this->item->catid === '12'  &&  $this->item->id === '11') : ?>
		<?=JModuleHelper::renderModule($modules[0]);?>
	<?php endif; ?>

	<?php // Content is generated by content plugin event "onContentAfterDisplay" ?>
	<?php echo $this->item->event->afterDisplayContent; ?>
</div>
